"""add homework mistakes and settings tables

Revision ID: a5ed36dbabf9
Revises: 1d0567bc331b
Create Date: 2026-09-05 22:29:57.209296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ed36dbabf9'
down_revision: Union[str, Sequence[str], None] = '1d0567bc331b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_date'), 'notification_logs', ['date'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_label', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('homework_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_items_date'), 'homework_items', ['date'], unique=False)
    op.create_index(op.f('ix_homework_items_id'), 'homework_items', ['id'], unique=False)
    op.create_index(op.f('ix_homework_items_is_completed'), 'homework_items', ['is_completed'], unique=False)
    op.create_index(op.f('ix_homework_items_student_id'), 'homework_items', ['student_id'], unique=False)
    op.create_index(op.f('ix_homework_items_subject_id'), 'homework_items', ['subject_id'], unique=False)
    op.create_table('mistake_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('original_image_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('cropped_diagram_path', sa.String(length=255), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('mastery_status', sa.String(length=20), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_records_id'), 'mistake_records', ['id'], unique=False)
    op.create_index(op.f('ix_mistake_records_mastery_status'), 'mistake_records', ['mastery_status'], unique=False)
    op.create_index(op.f('ix_mistake_records_next_review_date'), 'mistake_records', ['next_review_date'], unique=False)
    op.create_index(op.f('ix_mistake_records_source_type'), 'mistake_records', ['source_type'], unique=False)
    op.create_index(op.f('ix_mistake_records_student_id'), 'mistake_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_mistake_records_subject_id'), 'mistake_records', ['subject_id'], unique=False)
    op.create_table('mistake_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mistake_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistake_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistake_reviews_id'), 'mistake_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_mistake_reviews_mistake_id'), 'mistake_reviews', ['mistake_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistake_reviews_mistake_id'), table_name='mistake_reviews')
    op.drop_index(op.f('ix_mistake_reviews_id'), table_name='mistake_reviews')
    op.drop_table('mistake_reviews')
    op.drop_index(op.f('ix_mistake_records_subject_id'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_student_id'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_source_type'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_next_review_date'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_mastery_status'), table_name='mistake_records')
    op.drop_index(op.f('ix_mistake_records_id'), table_name='mistake_records')
    op.drop_table('mistake_records')
    op.drop_index(op.f('ix_homework_items_subject_id'), table_name='homework_items')
    op.drop_index(op.f('ix_homework_items_student_id'), table_name='homework_items')
    op.drop_index(op.f('ix_homework_items_is_completed'), table_name='homework_items')
    op.drop_index(op.f('ix_homework_items_id'), table_name='homework_items')
    op.drop_index(op.f('ix_homework_items_date'), table_name='homework_items')
    op.drop_table('homework_items')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_notification_logs_date'), table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
