"""create_papers_table

Revision ID: a664048047b8
Revises: 63d716a523ac
Create Date: 2026-09-06 12:13:14.743011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a664048047b8'
down_revision: Union[str, Sequence[str], None] = '63d716a523ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('mistake_ids', sa.Text(), nullable=False),
    sa.Column('sort_by', sa.String(length=20), nullable=True),
    sa.Column('space_level', sa.String(length=20), nullable=True),
    sa.Column('style_mode', sa.String(length=20), nullable=True),
    sa.Column('show_error_type', sa.Boolean(), nullable=True),
    sa.Column('estimated_pages', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_created_at'), 'papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_papers_status'), 'papers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_status'), table_name='papers')
    op.drop_index(op.f('ix_papers_created_at'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
